import type { UnifiedMarket, Platform } from './markets/types';

export type { Platform };

export const MOCK_MARKETS: UnifiedMarket[] = [
  {
    id: 'poly:fed-rate-march-2026',
    externalId: 'fed-rate-march-2026',
    platform: 'polymarket',
    slug: 'fed-interest-rate-cut-march-2026',
    url: 'https://polymarket.com/event/fed-interest-rate-cut-march-2026',
    title: 'Fed Interest Rate Cut in March 2026?',
    category: 'Economics',
    marketType: 'binary',
    outcomes: [
      { name: 'Yes', price: 0.12 },
      { name: 'No', price: 0.88 },
    ],
    yesPrice: 0.12,
    noPrice: 0.88,
    volume: 4_500_000,
    volume24h: 150_000,
    endDate: new Date('2026-03-31'),
    createdAt: new Date('2025-01-01'),
    status: 'open',
    trending: true,
  },
  {
    id: 'kalshi:bitcoin-100k-2025',
    externalId: 'bitcoin-100k-2025',
    platform: 'kalshi',
    slug: 'bitcoin-100k-end-2025',
    url: 'https://kalshi.com/markets/bitcoin-100k-end-2025',
    title: 'Bitcoin > $100k by End of 2025',
    category: 'Crypto',
    marketType: 'binary',
    outcomes: [
      { name: 'Yes', price: 0.45 },
      { name: 'No', price: 0.55 },
    ],
    yesPrice: 0.45,
    noPrice: 0.55,
    volume: 12_100_000,
    volume24h: 500_000,
    endDate: new Date('2025-12-31'),
    createdAt: new Date('2024-06-01'),
    status: 'open',
    trending: true,
  },
  {
    id: 'poly:nba-lakers-celtics',
    externalId: 'nba-lakers-celtics',
    platform: 'polymarket',
    slug: 'nba-finals-lakers-celtics',
    url: 'https://polymarket.com/event/nba-finals-lakers-celtics',
    title: 'NBA Finals: Lakers vs Celtics',
    category: 'Sports',
    marketType: 'matchup',
    outcomes: [
      { name: 'Lakers', price: 0.52 },
      { name: 'Celtics', price: 0.48 },
    ],
    yesPrice: 0.52,
    noPrice: 0.48,
    volume: 890_000,
    volume24h: 50_000,
    endDate: new Date('2025-06-15'),
    createdAt: new Date('2025-01-01'),
    status: 'open',
  },
  {
    id: 'kalshi:sp500-6000',
    externalId: 'sp500-6000',
    platform: 'kalshi',
    slug: 'sp500-close-6000',
    url: 'https://kalshi.com/markets/sp500-close-6000',
    title: 'S&P 500 Daily Close > 6000',
    category: 'Finance',
    marketType: 'binary',
    outcomes: [
      { name: 'Yes', price: 0.82 },
      { name: 'No', price: 0.18 },
    ],
    yesPrice: 0.82,
    noPrice: 0.18,
    volume: 2_300_000,
    volume24h: 200_000,
    endDate: new Date('2025-12-31'),
    createdAt: new Date('2024-09-01'),
    status: 'open',
  },
  {
    id: 'poly:oscars-best-actor',
    externalId: 'oscars-best-actor',
    platform: 'polymarket',
    slug: 'oscars-2026-best-actor',
    url: 'https://polymarket.com/event/oscars-2026-best-actor',
    title: 'Best Actor Oscar 2026',
    category: 'Entertainment',
    marketType: 'multi-option',
    outcomes: [
      { name: 'Timothée Chalamet', price: 0.35 },
      { name: 'Austin Butler', price: 0.28 },
      { name: 'Paul Mescal', price: 0.22 },
      { name: 'Other', price: 0.15 },
    ],
    yesPrice: 0.35,
    noPrice: 0.65,
    volume: 1_100_000,
    volume24h: 80_000,
    endDate: new Date('2026-03-01'),
    createdAt: new Date('2024-12-01'),
    status: 'open',
    trending: true,
  },
  {
    id: 'kalshi:nyc-temp-july4',
    externalId: 'nyc-temp-july4',
    platform: 'kalshi',
    slug: 'nyc-temp-90-july4',
    url: 'https://kalshi.com/markets/nyc-temp-90-july4',
    title: 'NYC Temperature > 90°F on July 4th',
    category: 'Weather',
    marketType: 'binary',
    outcomes: [
      { name: 'Yes', price: 0.33 },
      { name: 'No', price: 0.67 },
    ],
    yesPrice: 0.33,
    noPrice: 0.67,
    volume: 45_000,
    volume24h: 5_000,
    endDate: new Date('2025-07-04'),
    createdAt: new Date('2025-01-01'),
    status: 'open',
  },
  {
    id: 'poly:superbowl-2026',
    externalId: 'superbowl-2026',
    platform: 'polymarket',
    slug: 'superbowl-2026-winner',
    url: 'https://polymarket.com/event/superbowl-2026-winner',
    title: 'Super Bowl 2026 Winner',
    category: 'Sports',
    marketType: 'multi-option',
    outcomes: [
      { name: 'Chiefs', price: 0.22 },
      { name: 'Eagles', price: 0.18 },
      { name: 'Bills', price: 0.15 },
      { name: '49ers', price: 0.12 },
      { name: 'Other', price: 0.33 },
    ],
    yesPrice: 0.22,
    noPrice: 0.78,
    volume: 3_400_000,
    volume24h: 250_000,
    endDate: new Date('2026-02-08'),
    createdAt: new Date('2024-10-01'),
    status: 'open',
    trending: true,
  },
];
