'use client';

import React, { useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence, LayoutGroup } from 'framer-motion';
import { SmallGhostLogo } from './components/SmallGhostLogo';
import InputInterface from './components/InputInterface';
import ResponseDisplay from './components/ResponseDisplay';
import UserMessage from './components/UserMessage';
import ChatHistory from './components/ChatHistory';
import { useChatStore } from './store';
import { v4 as uuidv4 } from 'uuid';

const MOCK_RESPONSE = `Maxwell's equations are a set of coupled partial differential equations that form the foundation of classical electromagnetism, classical optics, and electric circuits. They describe how electric and magnetic fields are generated by charges, currents, and changes of the fields. An important consequence of the equations is that they demonstrate how fluctuating electric and magnetic fields propagate at a constant speed (c) in a vacuum, known as electromagnetic radiation.`;

const blurVariants = {
  relaxed: { opacity: 0 },
  active: { opacity: 1 }
};

const spacerVariants = {
  relaxed: { height: '30vh' },
  active: { height: '150px' }
};

export default function Home() {
  const {
    agentState,
    addMessage,
    setAgentState,
    getActiveSession,
    createSession,
    hasHydrated,
    activeSessionId
  } = useChatStore();

  const [currentLayout, setCurrentLayout] = useState<'relaxed' | 'active'>('relaxed');
  const scrollRef = useRef<HTMLDivElement>(null);

  // Track which messages are "history" (already rendered) vs "new" (just added)
  const historyIds = useRef(new Set<string>());
  const renderedSessionId = useRef(activeSessionId);

  // Initialize session if needed
  useEffect(() => {
    if (hasHydrated && !activeSessionId) {
      createSession();
    }
  }, [hasHydrated, activeSessionId, createSession]);

  // Get active messages
  const activeSession = getActiveSession();
  const messages = activeSession?.messages || [];

  // Update history tracking when session changes
  if (renderedSessionId.current !== activeSessionId) {
    // We just switched sessions!
    // Mark ALL current messages as history so they don't animate individually
    historyIds.current = new Set(messages.map(m => m.id));
    renderedSessionId.current = activeSessionId;
  } else {
    // Same session, but maybe new messages added?
    // We don't add them to historyIds here, so they WILL animate.
    // But we should add them *after* render so next time they are history?
    // Actually, we only care about the *initial load* of the session.
    // If we add a message, it animates. If we reload the page, it's history.
    // Wait, if we add a message, it's not in historyIds, so it animates. Good.
    // If we re-render for some other reason, it's still not in historyIds...
    // So it might re-animate if the parent re-renders?
    // No, Framer Motion handles re-renders fine unless key changes.
    // But we should probably add them to historyIds *after* they have been shown once?
    // For now, let's stick to "Session Switch" logic.
  }

  // Auto-scroll to bottom
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, agentState]);

  // Update layout based on state
  useEffect(() => {
    if (agentState !== 'relaxed' || messages.length > 0) {
      setCurrentLayout('active');
    } else {
      setCurrentLayout('relaxed');
    }
  }, [agentState, messages.length]);

  const handleQuery = (q: string) => {
    addMessage(q, 'user');

    setAgentState('thinking');

    setTimeout(() => {
      setAgentState('orchestrating');
    }, 2000);

    setTimeout(() => {
      setAgentState('synthesizing');
    }, 4500);

    setTimeout(() => {
      setAgentState('complete');
      addMessage(MOCK_RESPONSE, 'agent', true);
    }, 6000);
  };

  // Prevent hydration mismatch
  if (!hasHydrated) return null;

  return (
    <main className="relative min-h-screen w-full bg-[var(--bg-primary)] overflow-hidden selection:bg-brand-accent/30 font-sans">
      <ChatHistory />

      {/* GLOBAL EFFECTS */}
      <div className="bg-grain opacity-20 pointer-events-none fixed inset-0 z-0" />

      {/* VIGNETTE - Kaiyros Aesthetic */}
      <div className="fixed inset-0 pointer-events-none z-0 bg-[radial-gradient(circle_at_center,_transparent_0%,_var(--bg-primary)_100%),_radial-gradient(circle_at_center,_transparent_0%,_rgba(0,0,0,0.4)_100%)]" />

      {/* LAYOUT TRANSITIONS */}
      <AnimatePresence mode="wait">
        {currentLayout === 'relaxed' ? (
          <motion.div
            key="relaxed-layout"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, transition: { duration: 0.2 } }}
            className="fixed inset-0 flex flex-col items-center justify-center z-30 pointer-events-none"
          >
            <div className="pointer-events-auto flex flex-col items-center w-full max-w-3xl px-4">
              {/* Ghost Centered */}
              <motion.div
                initial={{ opacity: 0, scale: 0.9, filter: 'blur(10px)' }}
                animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }}
                exit={{ opacity: 0, scale: 0.9, filter: 'blur(10px)' }}
                transition={{ duration: 0.5, ease: [0.23, 1, 0.32, 1] }} // Cubic bezier for "premium" feel
                className="w-[160px] h-[200px] mb-8"
              >
                <SmallGhostLogo />
              </motion.div>

              {/* Input Centered */}
              <motion.div
                initial={{ opacity: 0, y: 20, filter: 'blur(5px)' }}
                animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                exit={{ opacity: 0, y: 20, filter: 'blur(5px)' }}
                transition={{ duration: 0.4, delay: 0.1, ease: 'easeOut' }}
                className="w-full"
              >
                <InputInterface state={agentState} hasMessages={messages.length > 0} onQuery={handleQuery} />
              </motion.div>
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="active-layout"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-30 pointer-events-none"
          >
            {/* Ghost - Smart Fixed Header */}
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.4, ease: 'easeOut' }}
              className="fixed top-0 left-0 w-full z-30 flex justify-center pointer-events-none"
            >
              <div className="w-full max-w-4xl px-4 md:px-6 pt-8">
                <div className="w-full max-w-3xl mx-auto">
                  <div className="w-[42px] h-[52px]">
                    <SmallGhostLogo />
                  </div>
                </div>
              </div>
            </motion.div>


            {/* Input Bottom */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 20 }}
              transition={{ duration: 0.4, ease: 'easeOut' }}
              className="fixed bottom-0 left-0 w-full z-30 px-4 pb-6 flex justify-center pointer-events-auto"
            >
              <div className="w-full max-w-3xl">
                <InputInterface state={agentState} hasMessages={messages.length > 0} onQuery={handleQuery} />
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>



      {/* CONTENT LAYER */}
      <div className="relative z-10 w-full h-screen flex flex-col">

        {/* Scrollable Chat Area */}
        <div
          ref={scrollRef}
          className="flex-1 overflow-y-auto w-full flex flex-col items-center scroll-smooth no-scrollbar"
          style={{
            maskImage: 'linear-gradient(to bottom, transparent 0%, black 200px, black calc(100% - 300px), transparent calc(100% - 100px))',
            WebkitMaskImage: 'linear-gradient(to bottom, transparent 0%, black 200px, black calc(100% - 300px), transparent calc(100% - 100px))'
          }}
        >
          {/* Spacer */}
          <motion.div
            variants={spacerVariants}
            initial="relaxed"
            animate={currentLayout}
            transition={{ duration: 0.5 }}
            className="shrink-0 w-full"
          />

          {/* Message List */}
          <div className="w-full max-w-4xl px-4 md:px-6 pb-40 flex flex-col gap-6">
            <AnimatePresence mode="popLayout">
              <motion.div
                key={activeSessionId} // Re-mounts the list container on session switch
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.4, ease: 'easeOut' }}
                className="flex flex-col gap-6 w-full"
              >
                {messages.map((msg) => {
                  // Check if this message is part of the "history" load
                  // If we just switched sessions, we want to treat existing messages as history
                  // New messages added *after* the switch will animate normally
                  const isHistory = historyIds.current.has(msg.id);

                  return (
                    <div key={msg.id} className="w-full">
                      {msg.role === 'user' ? (
                        <UserMessage content={msg.content} isHistory={isHistory} />
                      ) : (
                        <ResponseDisplay message={msg} isHistory={isHistory} />
                      )}
                    </div>
                  );
                })}
              </motion.div>
            </AnimatePresence>

            {/* Processing Indicator */}
            <AnimatePresence>
              {agentState !== 'relaxed' && agentState !== 'complete' && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  className="w-full max-w-3xl mx-auto mt-2 mb-12 flex items-center gap-3"
                >
                  <motion.div
                    className="w-2 h-2 rounded-full bg-brand-accent shadow-[0_0_10px_rgba(111,59,245,0.5)]"
                    animate={{ scale: [1, 1.5, 1], opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1.5, repeat: Infinity }}
                  />
                  <span className="text-[11px] font-medium text-white/40 uppercase tracking-[0.2em]">
                    {agentState}...
                  </span>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

    </main>
  );
}
