'use client';

import React, { useEffect, useRef } from 'react';
import { motion, AnimatePresence, LayoutGroup } from 'framer-motion';
import { SmallGhostLogo } from './components/SmallGhostLogo';
import InputInterface from './components/InputInterface';
import ResponseDisplay from './components/ResponseDisplay';
import UserMessage from './components/UserMessage';
import { useChatStore } from './store';
import { v4 as uuidv4 } from 'uuid';

const MOCK_RESPONSE = `Maxwell's equations are a set of coupled partial differential equations that form the foundation of classical electromagnetism, classical optics, and electric circuits. They describe how electric and magnetic fields are generated by charges, currents, and changes of the fields. An important consequence of the equations is that they demonstrate how fluctuating electric and magnetic fields propagate at a constant speed (c) in a vacuum, known as electromagnetic radiation.`;

const blurVariants = {
  relaxed: { opacity: 0 },
  active: { opacity: 1 }
};

const spacerVariants = {
  relaxed: { height: '30vh' },
  active: { height: '150px' }
};

export default function Home() {
  const { messages, agentState, addMessage, setAgentState } = useChatStore();
  const scrollRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, agentState]);

  const handleQuery = (q: string) => {
    addMessage({
      id: uuidv4(),
      role: 'user',
      content: q
    });

    setAgentState('thinking');

    setTimeout(() => {
      setAgentState('orchestrating');
    }, 2000);

    setTimeout(() => {
      setAgentState('synthesizing');
    }, 4500);

    setTimeout(() => {
      setAgentState('complete');
      addMessage({
        id: uuidv4(),
        role: 'agent',
        content: MOCK_RESPONSE,
        verified: true
      });
    }, 6000);
  };

  // Simple boolean - stable across renders
  const hasMessages = messages.length > 0;
  const currentLayout = hasMessages ? 'active' : 'relaxed';

  return (
    <main className="relative min-h-screen w-full bg-[var(--bg-primary)] overflow-hidden selection:bg-brand-accent/30 font-sans">

      {/* GLOBAL EFFECTS */}
      <div className="bg-grain" />

      {/* VIGNETTE - Kaiyros Aesthetic */}
      <div className="fixed inset-0 pointer-events-none z-0 bg-[radial-gradient(circle_at_center,_transparent_0%,_var(--bg-primary)_100%),_radial-gradient(circle_at_center,_transparent_0%,_rgba(0,0,0,0.4)_100%)]" />

      {/* LAYOUT TRANSITIONS */}
      <LayoutGroup>
        {currentLayout === 'relaxed' ? (
          <div className="fixed inset-0 flex flex-col items-center justify-center z-30 pointer-events-none">
            <div className="pointer-events-auto flex flex-col items-center w-full max-w-3xl px-4">
              {/* Ghost Centered */}
              <motion.div
                layoutId="ghost-logo"
                className="w-[160px] h-[200px] mb-8"
                transition={{ type: 'spring', stiffness: 300, damping: 40 }}
              >
                <SmallGhostLogo />
              </motion.div>

              {/* Input Centered */}
              <motion.div
                layoutId="input-area"
                className="w-full"
                transition={{ type: 'spring', stiffness: 300, damping: 40 }}
              >
                <InputInterface state={agentState} onQuery={handleQuery} />
              </motion.div>
            </div>
          </div>
        ) : (
          <>
            {/* Ghost - Smart Fixed Header */}
            <motion.div
              layoutId="ghost-logo"
              className="fixed top-0 left-0 w-full z-30 flex justify-center pointer-events-none"
              transition={{ type: 'spring', stiffness: 300, damping: 40 }}
            >
              <div className="w-full max-w-4xl px-4 md:px-6 pt-8">
                <div className="w-full max-w-3xl mx-auto">
                  <div className="w-[42px] h-[52px]">
                    <SmallGhostLogo />
                  </div>
                </div>
              </div>
            </motion.div>


            {/* Input Bottom */}
            <motion.div
              layoutId="input-area"
              className="fixed bottom-0 left-0 w-full z-30 px-4 pb-6 flex justify-center"
              transition={{ type: 'spring', stiffness: 300, damping: 40 }}
            >
              <div className="w-full max-w-3xl">
                <InputInterface state={agentState} onQuery={handleQuery} />
              </div>
            </motion.div>
          </>
        )}
      </LayoutGroup>



      {/* CONTENT LAYER */}
      <div className="relative z-10 w-full h-screen flex flex-col">

        {/* Scrollable Chat Area */}
        <div
          ref={scrollRef}
          className="flex-1 overflow-y-auto w-full flex flex-col items-center scroll-smooth no-scrollbar"
          style={{
            maskImage: 'linear-gradient(to bottom, transparent 0%, black 200px, black calc(100% - 300px), transparent calc(100% - 100px))',
            WebkitMaskImage: 'linear-gradient(to bottom, transparent 0%, black 200px, black calc(100% - 300px), transparent calc(100% - 100px))'
          }}
        >
          {/* Spacer */}
          <motion.div
            variants={spacerVariants}
            initial="relaxed"
            animate={currentLayout}
            transition={{ duration: 0.5 }}
            className="shrink-0 w-full"
          />

          {/* Message List */}
          <div className="w-full max-w-4xl px-4 md:px-6 pb-40 flex flex-col gap-6">


            <AnimatePresence mode="popLayout">
              {messages.map((msg) => (
                <div key={msg.id} className="w-full">
                  {msg.role === 'user' ? (
                    <UserMessage content={msg.content} />
                  ) : (
                    <ResponseDisplay message={msg} />
                  )}
                </div>
              ))}
            </AnimatePresence>

            {/* Processing Indicator */}
            <AnimatePresence>
              {agentState !== 'relaxed' && agentState !== 'complete' && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  className="w-full max-w-3xl mx-auto mt-2 mb-12 flex items-center gap-3"
                >
                  <motion.div
                    className="w-2 h-2 rounded-full bg-brand-accent shadow-[0_0_10px_rgba(111,59,245,0.5)]"
                    animate={{ scale: [1, 1.5, 1], opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1.5, repeat: Infinity }}
                  />
                  <span className="text-[11px] font-medium text-white/40 uppercase tracking-[0.2em]">
                    {agentState}...
                  </span>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

    </main>
  );
}
