import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, ChevronUp } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { PanelFrame } from './primitives/PanelFrame';
import { MaxwellIntelligence } from '@/app/lib/maxwell/types';
import { cn } from '@/app/lib/utils';

interface IntelligenceSummaryProps {
  intelligence: MaxwellIntelligence;
}

export function IntelligenceSummary({ intelligence }: IntelligenceSummaryProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  if (!intelligence?.raw?.adjudication) return null;

  return (
    <PanelFrame className="p-0 overflow-hidden relative bg-[#121214] border border-white/[0.08] rounded-md">
      <button 
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between p-4 lg:px-6 lg:py-4 hover:bg-white/[0.02] transition-colors group"
      >
        <div className="flex items-center gap-3">
          <div className="text-left">
            <h3 className="text-sm font-medium text-white/90">Executive Summary</h3>
            <p className="text-[10px] text-white/40 font-mono mt-0.5 tracking-wider uppercase">
              Generated by Claude 3.5 Sonnet • {intelligence.raw.adjudication.length} chars
            </p>
          </div>
        </div>
        
        <div className={cn(
          "p-1.5 rounded-md transition-all duration-200",
          isExpanded ? "bg-white/10 text-white" : "text-white/40 hover:text-white hover:bg-white/5"
        )}>
          {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.23, 1, 0.32, 1] }}
          >
            <div className="px-4 lg:px-6 pb-6 lg:pb-8">
              <div className="pt-4 border-t border-white/5">
                <div className="prose prose-invert prose-sm max-w-none">
                    <ReactMarkdown
                      components={{
                        h1: ({node, ...props}) => <h1 className="text-white/90 font-medium mb-3 mt-6 text-lg" {...props} />,
                        h2: ({node, ...props}) => <h2 className="text-white/90 font-medium mb-3 mt-6 text-base" {...props} />,
                        h3: ({node, ...props}) => <h3 className="text-white/90 font-medium mb-2 mt-4 text-sm" {...props} />,
                        p: ({node, ...props}) => <p className="text-white/70 leading-relaxed mb-4 text-sm font-sans" {...props} />,
                        ul: ({node, ...props}) => <ul className="list-disc pl-4 mb-4 space-y-1" {...props} />,
                        li: ({node, ...props}) => <li className="text-white/70 pl-1 text-sm font-sans" {...props} />,
                        strong: ({node, ...props}) => <strong className="text-white font-medium" {...props} />,
                      }}
                    >
                    {intelligence.raw.adjudication}
                  </ReactMarkdown>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </PanelFrame>
  );
}
